namespace UnityServer.Share
{
    public enum PacketType
    {
        ChatRequest = 1,
        PlayerMoveRequest = 3,
        PlayerLeaveRequest = 4,
        RespawnRequest = 5,
        SignupRequest = 6,
        SigninRequest = 7,
        AttendanceRequest = 8,
        AttackRequest = 9,
        MoveMapRequest = 11,
        ItemDropRequest = 13,
        ItemUseRequest = 14,
        ItemMoveRequest = 15,
        GroundItemGetRequest = 16,
        TokenLoginRequest = 17,

        SignupResponse = 100,
        SigninResponse = 102,
        AttendanceResponse = 103,
        AttackResponse = 104,
        MoveMapResponse = 105,
        ItemDropResponse = 107,
        ItemUseResponse = 108,
        ItemMoveResponse = 109,
        GroundItemGetResponse = 110,

        ChatNotify = 200,
        PlayerMoveNotify = 201,
        PlayerSpawnNotify = 202,
        PlayerLeaveNotify = 203,
        AssignPlayerIdNotify = 204,
        EnterCompleteNotify = 205,
        PlayerStatsNotify = 206,
        HpChangeNotify = 207,
        MpChangeNotify = 208,
        ExpChangeNotify = 209,
        LevelUpNotify = 210,
        PlayerDeathNotify = 211,
        RespawnNotify = 212,
        AttendanceNotify = 213,
        AttackNotify = 214,
        DamageNotify = 215,
        MonsterSpawnNotify = 216,
        MonsterDeathNotify = 217,
        MonsterDamageNotify = 218,
        ItemAddNotify = 219,
        GroundItemSpawnNotify = 220,
        GroundItemDespawnNotify = 221,
        MonsterMoveNotify = 222,
    }
}
